//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkDbFirst.DbContex
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public Nullable<System.Guid> Uid { get; set; }
        public Nullable<int> ArticleId { get; set; }
        public string Author { get; set; }
        public string Text { get; set; }
    
        public virtual Article Article { get; set; }
    }
}
